---
- name: download samba
  unarchive:
    src: "https://download.samba.org/pub/samba/stable/{{ install_samba_version }}.tar.gz"
    dest: "{{ install_samba_download }}"
    remote_src: yes

- name: configure samba
  command: > 
    ./configure 
    --prefix={{ install_samba_prefix }} 
    --sbindir={{ install_samba_sbin }} 
    --bindir={{ install_samba_bin }} 
    --sysconfdir={{ install_samba_etc }} 
    --mandir=/usr/share/man 
    --with-systemd
  args:
    chdir: "{{ install_samba_download }}/{{ install_samba_version }}"

- name: make
  make:
    chdir: "{{ install_samba_download }}/{{ install_samba_version }}"

- name: make install
  make:
    chdir: "{{ install_samba_download }}/{{ install_samba_version }}"
    target: install
