---
- name: download samba
  unarchive:
    src: "https://download.samba.org/pub/samba/stable/{{ samba_version }}.tar.gz"
    dest: "{{ samba_download }}"
    remote_src: yes

- name: configure samba
  shell: "./configure --prefix={{samba_prefix}} --sbindir=/sbin --bindir=/bin --sysconfdir=/etc/samba --mandir=/usr/share/man --with-systemd"
  args:
    chdir: "{{ samba_download }}/{{ samba_version }}"

- name: make
  make:
    chdir: "{{ samba_download }}/{{ samba_version }}"

#- name: make install
#  shell: "make install"
#  args:
#    chdir: "{{ samba_download }}/{{ samba_version }}"

- name: make install
  make:
    chdir: "{{ samba_download }}/{{ samba_version }}"
    target: install
