---
- name: instalação das dependendências do samba 4
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    # oficial from samba.org
    - acl
    - attr
    - autoconf
    - bind9utils
    - bison
    - build-essential
    - debhelper
    - dnsutils
    - docbook-xml
    - docbook-xsl
    - flex
    - gdb
    - krb5-user
    - libacl1-dev
    - libaio-dev
    - libarchive-dev
    - libattr1-dev
    - libblkid-dev
    - libbsd-dev
    - libcap-dev
    - libcups2-dev
    - libgnutls28-dev
    - libgpgme11-dev
    - libjansson-dev
    - libjson-perl
    - libldap2-dev
    - libncurses5-dev
    - libpam0g-dev
    - libparse-yapp-perl
    - libpopt-dev
    - libreadline-dev
    - nettle-dev
    - perl
    - perl-modules
    - pkg-config
    - python-all-dev
    - python-crypto
    - python-dbg
    - python-dev
    - python-dnspython
    - python-gpg
    - python-markdown
    - python3-dev
    - python3-dnspython
    - python3-gpg
    - python3-markdown
    - xsltproc
    - zlib1g-dev
    # extras
    - resolvconf
    - valgrind
    - libpam-dev
    - libsasl2-dev
    - ntp

- name: download samba
  unarchive:
    src: "https://download.samba.org/pub/samba/stable/{{ samba_version }}.tar.gz"
    dest: "{{ download }}"
    remote_src: yes   

- name: configure samba
  shell: "cd {{ download }}/{{ samba_version }} && ./configure --enable-debug --enable-selftest --with-systemd"

- name: make
  make:
    chdir: "{{ download }}/{{ samba_version }}"

- name: make install
  shell: "cd {{ download }}/{{ samba_version }} && make install"
